### ISSUE TITLE
[경험분해] AI 관련 서비스 요청을 50번 초과하여 수행 시 Forbidden 과 같은 에러를 띄운다

### ISSUE THREAD

**Issue by stae1102** [depromeet/InsightOut-Server#157]
# AI 관련 서비스 정책

Chat GPT 요청을 50번 보내면 51번 부터 금지하기로 했기 때문에 유저의 요청 수를 기록해야 합니다!

@PracticeEveryday 

이 기능은 동현님께 부탁드려도 될까요?

## 구현 방법

일단 일별 50번까지 요청 가능하기 때문에 개인적으로 cache를 사용하면 좋겠다고 생각했어요.

TTL 사용 가능하고, 바로 k-v로 쿼리할 수도 있고, 별도로 RDB에서 관리할 필요가 없는 비정형 데이터라서 EC2에 있는 레디스 사용하는 거 어떠신가요??

redis는 저번에 보여드린 것처럼 redis service에서 사용하시면 됩니다!

**Comment by PracticeEveryday** [comment]
- 네네!! 이부분 제가 함께 해서 작업하겠습니다:)
- 이제 봤네용 ㅎㅎㅎㅎ

**Comment by stae1102** [comment]
유저마다 하루의 기준이 다르니까 Cron 돌려서 하루가 지날 때 Batch 잡 돌려서 패턴이 비슷한 애들 삭제하는 것도 좋을 지도??

https://myblog.opendocs.co.kr/archives/962

**Comment by PracticeEveryday** [comment]
완료해습니다 :)
