### ISSUE TITLE
[프롬프트] 프롬프트 50회 횟수 제한하기

### ISSUE THREAD

**Issue by PracticeEveryday** [depromeet/InsightOut-Server#224]
# 프롬프트 횟수 제한하기(50회)

- 아이디어
1. 유저가 프롬프트를 실행할 때 레디스에 실행한 횟수 count를 저장한다.
2. 50회 이상이라면 못사용한다고 알려준다.
3. 특정 유니크한 키 값을 생성하여 매일 자정 해당 키 값을 가진 캐시를 모두 초기화한다!

**Comment by PracticeEveryday** [comment]
#157  참고

**Comment by stae1102** [comment]
생각해보니까 refreshToken도 유니크한 키로 안 넣고 있었어서 저도 수정해서 PR 따로 올릴게요!
