### ISSUE TITLE
[경험분해/모아보기] 경험카드 모아보기에 ai 키워드까지 내려주기

### ISSUE THREAD

**Issue by stae1102** [depromeet/InsightOut-Server#234]
<img width="316" alt="image" src="https://github.com/depromeet/InsightOut-Server/assets/83271772/5a473d9a-c2d2-4241-b06b-6210c9ad2041">

<img width="360" alt="image" src="https://github.com/depromeet/InsightOut-Server/assets/83271772/e14612fe-13e0-469a-892e-66a615bcb194">

키워드 개헷갈려~~ 이렇게 통일해도 괜찮을까요?

**Comment by PracticeEveryday** [comment]
조와쒀!
