### ISSUE TITLE
추가 작업 해야 할 것 공유 

### ISSUE THREAD

**Issue by PracticeEveryday** [depromeet/InsightOut-Server#250]
## 추가 작업 내용 공유

1. AI 추천 자기소개서 내려주기 API
2. 경험 카드 하나에 대한 모든 정보 내려주기 API

성태님 경험 카드 보여주기 #243 PR에서 말씀드린 것처럼 
1. 처음 모아보기를 가져올 때 앞면 데이터를 다 보내주기
2. 뒷면을 보여 줄 때 뒷면에 필요한 데이터(AI 추천 자기소개서, STAR)는 API 쏴서 데이터 가져오기
     - star는 아래 이미지의 API로 가져옵니다.
<img width="578" alt="image" src="https://github.com/depromeet/InsightOut-Server/assets/97580759/a4039398-5c77-40fd-83dd-cc9b22fc571a">

     - AI 추천 자기소개서는 AI 추천 자기소개서만 내려주는 API를 만들어 드리기로 했습니다.
3. 경험 카드 하나에 대한 앞 뒷면 모든 정보 내려주기 API는 하나 있으면 좋겠다고 하셔서 추가적으로 만들어 놓겠습니다.

- 작업 공유 드립니다 의견 주세용 😄

**Comment by PracticeEveryday** [comment]
@stae1102 오후 비즈니스 후 저녁에 작업하겠습니다 😢 😢 😢 😢 😢 😢

**Comment by stae1102** [comment]
> 뒷면을 보여 줄 때 뒷면에 필요한 데이터(AI 추천 자기소개서, STAR)는 API 쏴서 데이터 가져오기
> star는 아래 이미지의 API로 가져옵니다.

이거 제가 짠 API인데 GET /experience/{experienceId}/star
로 하는 게 리소스를 가져오는 입장에서 좋아 보이네요

사실 RESTful하게 하려면 GET /experience/{experienceId}?situation=true&task=true&action=true&result=true 로 하는 게 베스트지만 일단 나중에 리팩토링 싹 조지시죠!
