### ISSUE TITLE
[Database] 데이터베이스 개선

### ISSUE THREAD

**Issue by stae1102** [depromeet/InsightOut-Server#285]
# ERD

![image](https://github.com/depromeet/InsightOut-Server/assets/83271772/1651ed52-b9b0-45ee-b90b-b96932e86746)

저 런칭 빨리 하고 싶어요... 그래야 QA도 하고 발표도 할 수 있어서.....

**Comment by PracticeEveryday** [comment]
후ㅜㅜㅠㅠ
