### ISSUE TITLE
[회원가입/로그인] 랜덤 닉네임 생성기 직접 만들기 - 외부 API 서버 내려감

### ISSUE THREAD

**Issue by stae1102** [depromeet/InsightOut-Server#286]
# 문제 상황

기존 닉네임 생성기가 다운돼버렸어요 ^^..

<img width="984" alt="image" src="https://github.com/depromeet/InsightOut-Server/assets/83271772/774e066f-da61-45b5-a4bf-32a6a7c87f8c">

**Comment by PracticeEveryday** [comment]
ㅋㅋㅋㅋㅋ 이거 영어는 라이브러리 있을텐데 한글 별명 생성기는 없나여?

**Comment by stae1102** [comment]
만들었읍니다..
